/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutoLoginTesterRouteImport } from './routes/auto-login-tester'
import { Route as ClarificationFormRouteImport } from './routes/clarification-form'
import { Route as ComparisonToolRouteImport } from './routes/comparison-tool'
import { Route as CustomReportGeneratorRouteImport } from './routes/custom-report-generator'
import { Route as EnrollmentReportAuditRouteImport } from './routes/enrollment-report-audit'
import { Route as NewClientPasswordSetupRouteImport } from './routes/new-client-password-setup'
import { Route as NewClientTestRecordsRouteImport } from './routes/new-client-test-records'
import { Route as RatesCalculatorRouteImport } from './routes/rates-calculator'
import { Route as SalaryFileAutomationRouteImport } from './routes/salary-file-automation'
import { Route as ScreenshotRouteImport } from './routes/screenshot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoLoginTesterRoute = AutoLoginTesterRouteImport.update({
  id: '/auto-login-tester',
  path: '/auto-login-tester',
  getParentRoute: () => rootRouteImport,
} as any)
const ClarificationFormRoute = ClarificationFormRouteImport.update({
  id: '/clarification-form',
  path: '/clarification-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonToolRoute = ComparisonToolRouteImport.update({
  id: '/comparison-tool',
  path: '/comparison-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomReportGeneratorRoute = CustomReportGeneratorRouteImport.update({
  id: '/custom-report-generator',
  path: '/custom-report-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentReportAuditRoute = EnrollmentReportAuditRouteImport.update({
  id: '/enrollment-report-audit',
  path: '/enrollment-report-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const NewClientPasswordSetupRoute = NewClientPasswordSetupRouteImport.update({
  id: '/new-client-password-setup',
  path: '/new-client-password-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const NewClientTestRecordsRoute = NewClientTestRecordsRouteImport.update({
  id: '/new-client-test-records',
  path: '/new-client-test-records',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesCalculatorRoute = RatesCalculatorRouteImport.update({
  id: '/rates-calculator',
  path: '/rates-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryFileAutomationRoute = SalaryFileAutomationRouteImport.update({
  id: '/salary-file-automation',
  path: '/salary-file-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotRoute = ScreenshotRouteImport.update({
  id: '/screenshot',
  path: '/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto-login-tester': typeof AutoLoginTesterRoute
  '/clarification-form': typeof ClarificationFormRoute
  '/comparison-tool': typeof ComparisonToolRoute
  '/custom-report-generator': typeof CustomReportGeneratorRoute
  '/enrollment-report-audit': typeof EnrollmentReportAuditRoute
  '/new-client-password-setup': typeof NewClientPasswordSetupRoute
  '/new-client-test-records': typeof NewClientTestRecordsRoute
  '/rates-calculator': typeof RatesCalculatorRoute
  '/salary-file-automation': typeof SalaryFileAutomationRoute
  '/screenshot': typeof ScreenshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto-login-tester': typeof AutoLoginTesterRoute
  '/clarification-form': typeof ClarificationFormRoute
  '/comparison-tool': typeof ComparisonToolRoute
  '/custom-report-generator': typeof CustomReportGeneratorRoute
  '/enrollment-report-audit': typeof EnrollmentReportAuditRoute
  '/new-client-password-setup': typeof NewClientPasswordSetupRoute
  '/new-client-test-records': typeof NewClientTestRecordsRoute
  '/rates-calculator': typeof RatesCalculatorRoute
  '/salary-file-automation': typeof SalaryFileAutomationRoute
  '/screenshot': typeof ScreenshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto-login-tester': typeof AutoLoginTesterRoute
  '/clarification-form': typeof ClarificationFormRoute
  '/comparison-tool': typeof ComparisonToolRoute
  '/custom-report-generator': typeof CustomReportGeneratorRoute
  '/enrollment-report-audit': typeof EnrollmentReportAuditRoute
  '/new-client-password-setup': typeof NewClientPasswordSetupRoute
  '/new-client-test-records': typeof NewClientTestRecordsRoute
  '/rates-calculator': typeof RatesCalculatorRoute
  '/salary-file-automation': typeof SalaryFileAutomationRoute
  '/screenshot': typeof ScreenshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auto-login-tester'
    | '/clarification-form'
    | '/comparison-tool'
    | '/custom-report-generator'
    | '/enrollment-report-audit'
    | '/new-client-password-setup'
    | '/new-client-test-records'
    | '/rates-calculator'
    | '/salary-file-automation'
    | '/screenshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auto-login-tester'
    | '/clarification-form'
    | '/comparison-tool'
    | '/custom-report-generator'
    | '/enrollment-report-audit'
    | '/new-client-password-setup'
    | '/new-client-test-records'
    | '/rates-calculator'
    | '/salary-file-automation'
    | '/screenshot'
  id:
    | '__root__'
    | '/'
    | '/auto-login-tester'
    | '/clarification-form'
    | '/comparison-tool'
    | '/custom-report-generator'
    | '/enrollment-report-audit'
    | '/new-client-password-setup'
    | '/new-client-test-records'
    | '/rates-calculator'
    | '/salary-file-automation'
    | '/screenshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoLoginTesterRoute: typeof AutoLoginTesterRoute
  ClarificationFormRoute: typeof ClarificationFormRoute
  ComparisonToolRoute: typeof ComparisonToolRoute
  CustomReportGeneratorRoute: typeof CustomReportGeneratorRoute
  EnrollmentReportAuditRoute: typeof EnrollmentReportAuditRoute
  NewClientPasswordSetupRoute: typeof NewClientPasswordSetupRoute
  NewClientTestRecordsRoute: typeof NewClientTestRecordsRoute
  RatesCalculatorRoute: typeof RatesCalculatorRoute
  SalaryFileAutomationRoute: typeof SalaryFileAutomationRoute
  ScreenshotRoute: typeof ScreenshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-login-tester': {
      id: '/auto-login-tester'
      path: '/auto-login-tester'
      fullPath: '/auto-login-tester'
      preLoaderRoute: typeof AutoLoginTesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clarification-form': {
      id: '/clarification-form'
      path: '/clarification-form'
      fullPath: '/clarification-form'
      preLoaderRoute: typeof ClarificationFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison-tool': {
      id: '/comparison-tool'
      path: '/comparison-tool'
      fullPath: '/comparison-tool'
      preLoaderRoute: typeof ComparisonToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-report-generator': {
      id: '/custom-report-generator'
      path: '/custom-report-generator'
      fullPath: '/custom-report-generator'
      preLoaderRoute: typeof CustomReportGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment-report-audit': {
      id: '/enrollment-report-audit'
      path: '/enrollment-report-audit'
      fullPath: '/enrollment-report-audit'
      preLoaderRoute: typeof EnrollmentReportAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-client-password-setup': {
      id: '/new-client-password-setup'
      path: '/new-client-password-setup'
      fullPath: '/new-client-password-setup'
      preLoaderRoute: typeof NewClientPasswordSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-client-test-records': {
      id: '/new-client-test-records'
      path: '/new-client-test-records'
      fullPath: '/new-client-test-records'
      preLoaderRoute: typeof NewClientTestRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates-calculator': {
      id: '/rates-calculator'
      path: '/rates-calculator'
      fullPath: '/rates-calculator'
      preLoaderRoute: typeof RatesCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-file-automation': {
      id: '/salary-file-automation'
      path: '/salary-file-automation'
      fullPath: '/salary-file-automation'
      preLoaderRoute: typeof SalaryFileAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshot': {
      id: '/screenshot'
      path: '/screenshot'
      fullPath: '/screenshot'
      preLoaderRoute: typeof ScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoLoginTesterRoute: AutoLoginTesterRoute,
  ClarificationFormRoute: ClarificationFormRoute,
  ComparisonToolRoute: ComparisonToolRoute,
  CustomReportGeneratorRoute: CustomReportGeneratorRoute,
  EnrollmentReportAuditRoute: EnrollmentReportAuditRoute,
  NewClientPasswordSetupRoute: NewClientPasswordSetupRoute,
  NewClientTestRecordsRoute: NewClientTestRecordsRoute,
  RatesCalculatorRoute: RatesCalculatorRoute,
  SalaryFileAutomationRoute: SalaryFileAutomationRoute,
  ScreenshotRoute: ScreenshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
